# CALM Model Configuration

project_path: "/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM/"

dataset:
    target_project: "GBMLGG"
    meta_data_path: "/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM/data/OS/tcga_gbmlgg_all.csv"
    split_path: "/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM/splits/OS/tcga_gbmlgg/"
    wsi_path: "/project/kimlab_tcga/TCGA_raw_image_data/tcga-gbmlgg/"
    wsi_file_ext: ".svs"
    image_feat_path: "/project/kimlab_tcga/Data/extracted_features/CLAM_prepared/tcga-gbmlgg"
    text_feat_path: "/project/kimlab_tcga/JH_workspace/multimodality_prognosis_prediction/CALM/data/TCGA_Reports_prepared.csv"
    omic_feat_path: 
    valid_size: 0.2
    random_state: 42

hyperparam:
    warmup_epochs: 10
    max_epochs: 100
    learning_rate: 1e-5

trainer_param:
    precision: 16
    gpus: 1
    accelerator: 'cuda'
    accumulate_grad_batches: 8
    num_sanity_val_steps: 0